### ISSUE TITLE
What command clears the table of records?

### ISSUE THREAD

**Issue by eduardvartanyan** [bozerkins/clickhouse-client#12]
What command clears the table of records?

**Comment by eduardvartanyan** [comment]
Issue resolved:
`$client->write("ALTER TABLE <table_name> DELETE WHERE <...>;");`

**Comment by bozerkins** [comment]
Hi, 
If you want to completely erase all the records, you can use `TRUNCATE TABLE`
https://clickhouse.com/docs/en/sql-reference/statements/truncate

Note that this operation is a blocking DDL statement (same as alter table), so shouldn't be run in parallel.

In case when you need to delete the data partially, you can also use `DROP PARTITION`. You would need to organize your data in partitions for this to work.
https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#drop-partitionpart

Latest ClickHouse versions support `DELETE` statement, the actual deletion of the data will happen asynchronously in background. 
https://clickhouse.com/docs/en/sql-reference/statements/delete
